github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true
    
image: public.ecr.aws/pahudnet/gitpod-workspace:latest
#   file: .gitpod.Dockerfile
tasks:
  - init: ${GITPOD_REPO_ROOT}/utils/init-script.sh

vscode:
  extensions:
    - dbaeumer.vscode-eslint
