github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true
    
image: public.ecr.aws/pahudnet/gitpod-workspace:latest
#   file: .gitpod.Dockerfile
tasks:
  - command: echo "source /usr/share/bash-completion/completions/git" >> $HOME/.bashrc


vscode:
  extensions:
    - dbaeumer.vscode-eslint
