name: Publish Docker image
on:
  schedule:
    # Every hour
    - cron: 37 * * * *
  workflow_dispatch: {}
  
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: VaultVulp/gp-docker-action@1.1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: gitpod-workspace # Provide only Docker image name, tag will be automatically set to latest
          dockerfile: .gitpod.Dockerfile

